const adsData = [
  {
    id: 1,
    title: "Conta Roblox com 50k Robux + Itens Raros",
    category: "roblox",
    categoryLabel: "Roblox",
    price: 189.90,
    seller: "ProGamer_BR",
    rating: 4.9,
    sales: 312,
    icon: "fa-cube",
    imgClass: "prod-roblox",
    description: "Conta original com 50.000 Robux, vários itens limitados, avatares exclusivos e histórico limpo. Entrega automática após confirmação do pagamento."
  },
  {
    id: 2,
    title: "Conta Valorant Imortal 3 - Full Skins",
    category: "valorant",
    categoryLabel: "Valorant",
    price: 349.00,
    seller: "ValorantKing",
    rating: 5.0,
    sales: 89,
    icon: "fa-crosshairs",
    imgClass: "prod-valorant",
    description: "Conta rank Imortal 3 com mais de 80 skins, incluindo bundles completos (Reaver, Prime, Elderflame). Email próprio e dados de recuperação inclusos."
  },
  {
    id: 3,
    title: "Conta Free Fire Diamante - Booyah Pass",
    category: "freefire",
    categoryLabel: "Free Fire",
    price: 79.90,
    seller: "FFMaster",
    rating: 4.8,
    sales: 520,
    icon: "fa-fire",
    imgClass: "prod-freefire",
    description: "Conta com nível alto, vários personagens lendários, skins de armas e Booyah Pass ativo. Entrega rápida via chat."
  },
  {
    id: 4,
    title: "Conta LoL Diamond - 150 Skins",
    category: "lol",
    categoryLabel: "League of Legends",
    price: 299.00,
    seller: "MidLaneGod",
    rating: 4.9,
    sales: 145,
    icon: "fa-dragon",
    imgClass: "prod-lol",
    description: "Conta Diamond IV com mais de 150 skins, vários campeões maxados e histórico competitivo limpo. Região BR."
  },
  {
    id: 5,
    title: "Conta Fortnite com Skins Raras",
    category: "fortnite",
    categoryLabel: "Fortnite",
    price: 220.00,
    seller: "FortniteBR",
    rating: 4.7,
    sales: 67,
    icon: "fa-parachute-box",
    imgClass: "prod-default",
    description: "Conta com skins exclusivas de temporadas antigas, V-Bucks e battle pass completo. Conta original com email."
  },
  {
    id: 6,
    title: "Conta Genshin Impact AR 60 - C6 Characters",
    category: "genshin",
    categoryLabel: "Genshin Impact",
    price: 450.00,
    seller: "GenshinPro",
    rating: 5.0,
    sales: 34,
    icon: "fa-magic",
    imgClass: "prod-genshin",
    description: "Conta Adventure Rank 60 com vários personagens C6, armas 5 estrelas e recursos abundantes. Servidor América."
  },
  {
    id: 7,
    title: "Spotify Premium 30 Dias (Via Link)",
    category: "premium",
    categoryLabel: "Assinaturas",
    price: 13.99,
    seller: "LINcontas",
    rating: 4.9,
    sales: 290,
    icon: "fab fa-spotify",
    imgClass: "prod-spotify",
    description: "Spotify Premium 30 dias via link. Não é conta compartilhada. Ativação rápida e suporte incluso."
  },
  {
    id: 8,
    title: "YouTube Premium 30 Dias",
    category: "premium",
    categoryLabel: "Assinaturas",
    price: 2.50,
    seller: "Tedlito_",
    rating: 4.8,
    sales: 8,
    icon: "fab fa-youtube",
    imgClass: "prod-youtube",
    description: "YouTube Premium 30 dias. Sem anúncios e com background play. Entrega automática."
  },
  {
    id: 9,
    title: "Robux Barato - Entrega Automática",
    category: "roblox",
    categoryLabel: "Roblox",
    price: 45.00,
    seller: "RobuxFast",
    rating: 4.8,
    sales: 1200,
    icon: "fa-cube",
    imgClass: "prod-roblox",
    description: "Pacote de 2.000 Robux com entrega automática 24h. Método seguro e rápido."
  },
  {
    id: 10,
    title: "Conta Valorant Radiant - Full Agents",
    category: "valorant",
    categoryLabel: "Valorant",
    price: 599.00,
    seller: "RadiantOnly",
    rating: 5.0,
    sales: 28,
    icon: "fa-crosshairs",
    imgClass: "prod-valorant",
    description: "Conta Radiant com todos os agentes desbloqueados e skins premium. Ideal para competição."
  },
  {
    id: 11,
    title: "Diamantes Free Fire - 10.000",
    category: "freefire",
    categoryLabel: "Free Fire",
    price: 120.00,
    seller: "DiamanteShop",
    rating: 4.6,
    sales: 890,
    icon: "fa-fire",
    imgClass: "prod-freefire",
    description: "10.000 diamantes com entrega via ID. Rápido e seguro."
  },
  {
    id: 12,
    title: "Netflix Premium 30 Dias",
    category: "premium",
    categoryLabel: "Assinaturas",
    price: 9.90,
    seller: "StreamBR",
    rating: 4.7,
    sales: 156,
    icon: "fas fa-film",
    imgClass: "prod-default",
    description: "Netflix Premium 30 dias. Perfil próprio, 4K disponível. Renovação mensal opcional."
  }
];
